const REQUEST_FILTERS = {
    'headers_service_token': req.headers['service_token'],
    'headers_user_id': req.headers['user_id'],
    'body_current_uri': req.body.current_uri,
    'body_ip_public': req.body.ip_public,
    'body_ip_private': req.body.ip_private,
    'body_time': req.body.time,
    'body_user_agent': req.body.user_agent,
    'body_secondsToLoad': req.body.secondsToLoad,
    'body_pauseCount': req.body.pauseCount,
    'body_seekCount': req.body.seekCount,
    'body_currentTime': req.body.currentTime,
    'body_duration': req.body.duration,
    'body_readyState': req.body.readyState, 
    'body_bufferCount': req.body.bufferCount,
    'body_totalDuration': req.body.totalDuration, 
    'body_watchedDuration': req.body.watchedDuration, 
    'body_bufferDuration': req.body.bufferDuration, 
    'body_initialLoadTime': req.body.initialLoadTime,
    'body_error_code': req.body.data.error_code,
    'body_error_type': req.body.data.error_type,
    'body_error_message': req.body.data.error_message,
    'body_media_id': req.body.media_id,
    'body_media_category': req.body.media_category,
    'body_media_name': req.body.media_name,
    'body_media_viewed': req.body.media_viewed,
    'body_media_like_count': req.body.media_like_count,
};

module.exports.REQUEST_FILTERS = REQUEST_FILTERS;
